"""add sensors and sensor logs

Revision ID: 2b3159db7ffa
Revises: 00e0910119d5
Create Date: 2026-03-14 10:29:42.253451

"""
from alembic import op
import sqlalchemy as sa


revision = '2b3159db7ffa'
down_revision = '00e0910119d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pond_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_logs')
    op.drop_table('sensors')
    # ### end Alembic commands ###
