"""add sensor logs

Revision ID: 6e28d1aeb75e
Revises: e07e09811879
Create Date: 2026-03-16 14:37:46.901818

"""
from alembic import op
import sqlalchemy as sa


revision = '6e28d1aeb75e'
down_revision = 'e07e09811879'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('sensor_logs_recorded_by_fkey'), 'sensor_logs', type_='foreignkey')
    op.drop_column('sensor_logs', 'recorded_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_logs', sa.Column('recorded_by', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('sensor_logs_recorded_by_fkey'), 'sensor_logs', 'users', ['recorded_by'], ['id'])
    op.drop_column('sensor_logs', 'created_at')
    # ### end Alembic commands ###
