"""add image_url to lands and ponds

Revision ID: e07e09811879
Revises: dc640697996e
Create Date: 2026-03-16 10:46:30.105688

"""
from alembic import op
import sqlalchemy as sa


revision = 'e07e09811879'
down_revision = 'dc640697996e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lands', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('ponds', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ponds', 'image_url')
    op.drop_column('lands', 'image_url')
    # ### end Alembic commands ###
